# Generated by Django 4.1.3 on 2022-11-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_workdetailspage_workdetailspagethumbnailimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workdetailspage',
            old_name='work_name',
            new_name='work_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro',
        ),
    ]
